os: osx
osx_image: xcode9.2
language: objective-c
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - PROJECT_FRAMEWORK=NOCLibraryFramework/NOCLibraryFramework.xcworkspace
    - SCHEME_FRAMEWORK=NOCLibraryFramework
    - SCHEME_UNIVERSAL=UniversalFramework
    - PROJECT_DEMO=Demo/NOCLibrary-Demo.xcworkspace
    - SCHEME_LIBRARY_DEMO=NOCLibrary-Demo
    - SCHEME_FRAMEWORK_DEMO=NOCLibraryFramework-Demo
    - IOS_SDK=iphonesimulator11.2
    - CONFIG_DEBUG="Debug"
    - CONFIG_RELEASE="Release"
  matrix:
    - POD_LINT="YES"
    - POD_LINT="NO" PROJECT_FILE="$PROJECT_FRAMEWORK" SCHEME="$SCHEME_FRAMEWORK"      SDK="$IOS_SDK"  CONFIG="$CONFIG_DEBUG"
    - POD_LINT="NO" PROJECT_FILE="$PROJECT_FRAMEWORK" SCHEME="$SCHEME_FRAMEWORK"      SDK="$IOS_SDK"  CONFIG="$CONFIG_RELEASE"
    - POD_LINT="NO" PROJECT_FILE="$PROJECT_FRAMEWORK" SCHEME="$SCHEME_UNIVERSAL"      SDK="$IOS_SDK"  CONFIG="$CONFIG_DEBUG"
    - POD_LINT="NO" PROJECT_FILE="$PROJECT_FRAMEWORK" SCHEME="$SCHEME_UNIVERSAL"      SDK="$IOS_SDK"  CONFIG="$CONFIG_RELEASE"
    - POD_LINT="NO" PROJECT_FILE="$PROJECT_DEMO"      SCHEME="$SCHEME_LIBRARY_DEMO"   SDK="$IOS_SDK"  CONFIG="$CONFIG_DEBUG"
    - POD_LINT="NO" PROJECT_FILE="$PROJECT_DEMO"      SCHEME="$SCHEME_LIBRARY_DEMO"   SDK="$IOS_SDK"  CONFIG="$CONFIG_RELEASE"
    - POD_LINT="NO" PROJECT_FILE="$PROJECT_DEMO"      SCHEME="$SCHEME_FRAMEWORK_DEMO" SDK="$IOS_SDK"  CONFIG="$CONFIG_DEBUG"
    - POD_LINT="NO" PROJECT_FILE="$PROJECT_DEMO"      SCHEME="$SCHEME_FRAMEWORK_DEMO" SDK="$IOS_SDK"  CONFIG="$CONFIG_RELEASE"
before_install:
  - brew update
  - gem install xcpretty
  - brew install cocoapods
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcrun simctl list
  - rm -rf ~/.cocoapods/repos/master
  - pod setup --verbose

  - if [ $POD_LINT == "YES" ]; then pod lib lint;  fi
  - if [ $POD_LINT == "YES" ]; then pod spec lint; fi

  - if [ $PROJECT_FILE == "$PROJECT_FRAMEWORK" ]; then cd NOCLibraryFramework; pod install; pod update; cd ../; fi
  - if [ $PROJECT_FILE == "$PROJECT_DEMO"      ]; then cd Demo;                pod install; pod update; cd ../; fi
  - if [ $POD_LINT == "NO" ]; then xcodebuild -workspace "$PROJECT_FILE" -scheme "$SCHEME" -configuration "$CONFIG" -sdk "$SDK" ONLY_ACTIVE_ARCH=NO clean build | xcpretty -c; fi
